### ISSUE TITLE
Reportportal extension selenium isn't sending data to reportportal service

### ISSUE THREAD

**Issue by testingplusme** [nvborisenko/reportportal-extensions-selenium#1] opened 2019-10-21 07:25 UTC
Hey Nikolay,
First of all, I need to appreciate what did you do :) It's awesome that you do this type of extension. I wanted to develop by myself but I see that you did it 👍 
I have a problem with the extension I added to my code your extension method but when I ran tests from NUnit Console Runner and it doesn't work. I have a connection with my reportportal because I can see that tests were running but without logs from the tests? Can you help me?

Best Regards,
Michal

**Comment by nvborisenko** [comment] 2019-10-21 07:57
Good to hear you are interesting it. Is it possible to create a very small test project to reproduce the issue?

**Comment by testingplusme** [comment] 2019-10-21 08:53
Ofc, I put my solution there -> It's working test reportportal service in my config so please test with it
https://github.com/testingplusme/ReportPortalExampleNet project SeleniumExampleTests

**Comment by nvborisenko** [comment] 2019-10-21 12:44
I reproduced it, and this is bug. As a workaround please install `NUnit3TestAdapter` nuget package and it will work.

**Comment by testingplusme** [comment] 2019-10-21 19:24
Thanks, it's working now :)

**Comment by nvborisenko** [comment] 2019-10-21 20:25
The issue is resolved in ReportPortal.NUnit v3.7.11. You are not required to apply workaround.

Thanks for the issue. I'm closing it.

**Closed as completed by nvborisenko** 2019-10-21 20:25 UTC
